### ISSUE TITLE
There are many duplicate instance names in aletsch result file

### ISSUE THREAD

**Issue by xiekunwhy** [Shao-Group/meta-scallop#2]
Hi,

There are many duplicate instance id in the results file, is there a way to avoid?

[dup.instance.zip](https://github.com/Shao-Group/aletsch/files/7880494/dup.instance.zip)

Best,
Kun

**Comment by shaomingfu** [comment]
We have fixed this in the new release.

**Comment by Jungal10** [comment]
Hi, we are doing some work looking for _denovo_ transcripts and we are facing this issue again. 
Roughly 0.5% of transcripts ids seem to have the same (duplicated) instances. This happens with exactly two instances per "duplicated instance"
Any idea on what might be causing it and potential solutions?

Thank you!

**Comment by Jungal10** [comment]
Hi, we are doing some work looking for _denovo_ transcripts and we are facing this issue again. 
Roughly 0.5% of  transcripts ids seem to have the same (duplicated) instances. This happens with exactly two instances per "duplicated instance"
Any idea on what might be causing it and potential solutions?

Thank you!

**Comment by rachelshiq** [comment]
Thank you for bringing this problem to our attention and we also notice this recently, which is due to output transcript from different strands sharing the same instance name. We have fixed this is the latest v1.1.3 version. If the same problem persists in this latest version, feel free to let us know.

**Comment by Jungal10** [comment]
> Thank you for bringing this problem to our attention and we also notice this recently, which is due to output transcript from different strands sharing the same instance name. We have fixed this is the latest v1.1.3 version. If the same problem persists in this latest version, feel free to let us know.


We just tested it and it is solved! Thank you so much for the lightning response.

P.S.: the version command still states the previous version, you might want to check it.
